version: "3.8"
services:
  app:
    expose:
      - 8080
    ports:
      - "8080:8080"
    container_name: taskmanagementsystem
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}