version: '3.8'
services:
  app:
    image: b48a06737930
    expose:
      - 8080
    ports:
      - "8080:8080"
    container_name: taskmanagementsystem
    working_dir: /app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_manager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=86040716-3BF1-4537-95B0-54F018CC6
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_SQL_SCHEMA-LOCATIONS=classpath:sql/schema.sql
      - SPRING_SQL_DATA-LOCATIONS=classpath:sql/data.sql
      - API_SERVER_URL=http://localhost:8080
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=86040716-3BF1-4537-95B0-54F018CC6